- name: Install MySQL on Debian familiy
  apt:
    name: mysql-server-8.0
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  
- name: Install MySQL on RedHat family
  yum:
    name: mysql-server-8.0
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
